# Generated by Django 2.1 on 2018-09-16 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_transacao_catergoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('tema', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('local', models.CharField(max_length=120)),
                ('Caregoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Caregoria')),
            ],
            options={
                'verbose_name_plural': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('dataNasc', models.DateTimeField()),
                ('cargo', models.CharField(max_length=150)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Funcionário',
            },
        ),
    ]
